version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: line_estimate
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - line-estimate-network

  backend:
    build:
      context: ./backend
      # 本番環境ではこちらを使用
      # dockerfile: Dockerfile
      # 開発環境ではこちらを使用
      dockerfile: Dockerfile.local
    ports:
      - "18080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://user:password@postgres:5432/line_estimate?sslmode=disable
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      # Google Drive Configuration
      - GOOGLE_SERVICE_ACCOUNT_KEY=/app/disposal-estimate-a107e828d351.json
      - GOOGLE_DRIVE_FOLDER_ID=1X0IQJWG6Ss47skLDgH_xkJGRGXmuE7Kf
      - SAVE_LOCAL_PDF=false
      # SSL/TLS settings for Google API
      - SSL_CERT_DIR=/etc/ssl/certs
      - CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    depends_on:
      - postgres
    networks:
      - line-estimate-network
    volumes:
      - ./backend:/app:delegated
      # Google Drive service account key file
      - ./backend/disposal-estimate-a107e828d351.json:/app/disposal-estimate-a107e828d351.json:ro

  frontend:
    build:
      context: ./frontend
      # 本番環境ではこちらを使用
      # dockerfile: Dockerfile
      # 開発環境ではこちらを使用
      dockerfile: Dockerfile.local
    ports:
      - "13000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080/api/v1
    depends_on:
      - backend
    networks:
      - line-estimate-network
    # 開発環境では volumes を有効化
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  line-estimate-network:
    driver: bridge
