// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/categories": {
            "get": {
                "description": "商品カテゴリーとアイテムの一覧を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "カテゴリー一覧を取得",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "ひらがなでソートするかどうか",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/estimates/": {
            "get": {
                "description": "すべての見積もりを取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Estimates"
                ],
                "summary": "見積もり一覧を取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "新しい見積もりを作成します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Estimates"
                ],
                "summary": "見積もりを作成",
                "parameters": [
                    {
                        "description": "見積もり情報",
                        "name": "estimate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateEstimateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Estimate"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/estimates/pdf": {
            "post": {
                "description": "見積もり情報からPDFを生成します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "Estimates"
                ],
                "summary": "見積もりPDFを生成",
                "parameters": [
                    {
                        "description": "見積もり情報",
                        "name": "estimate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PDFEstimate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/estimates/{id}": {
            "get": {
                "description": "IDを指定して見積もりを取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Estimates"
                ],
                "summary": "見積もりを取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "見積もりID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.Estimate"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "指定したIDの見積もりを更新します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Estimates"
                ],
                "summary": "見積もりを更新",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "見積もりID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新する見積もり情報",
                        "name": "estimate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateEstimateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "指定したIDの見積もりを削除します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Estimates"
                ],
                "summary": "見積もりを削除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "見積もりID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/instructions/pdf": {
            "post": {
                "description": "指示書情報からPDFを生成します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Instructions"
                ],
                "summary": "指示書PDFを生成",
                "parameters": [
                    {
                        "description": "指示書情報",
                        "name": "instruction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PDFInstruction"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/profile": {
            "get": {
                "description": "現在のユーザー情報を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "ユーザープロフィールを取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.User"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "ユーザー情報を更新します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "ユーザープロフィールを更新",
                "parameters": [
                    {
                        "description": "更新するユーザー情報",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dev/create-instruction-pdf": {
            "get": {
                "description": "開発用のテスト指示書PDFを生成します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Development"
                ],
                "summary": "テスト指示書PDFを生成",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dev/create-pdf": {
            "get": {
                "description": "開発用のテストPDFを生成します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "Development"
                ],
                "summary": "テストPDFを生成",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "APIの動作状態を確認します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "ヘルスチェック",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CreateEstimateRequest": {
            "type": "object",
            "required": [
                "hourly_rate",
                "title",
                "total_lines"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "hourly_rate": {
                    "type": "number",
                    "minimum": 0
                },
                "title": {
                    "type": "string"
                },
                "total_lines": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "models.Estimate": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "hourly_rate": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "total_cost": {
                    "type": "number"
                },
                "total_lines": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.PDFCollectorInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "住所",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "person": {
                    "description": "担当",
                    "type": "string"
                },
                "recipient": {
                    "description": "受付",
                    "type": "string"
                },
                "tel": {
                    "description": "TEL",
                    "type": "string"
                }
            }
        },
        "models.PDFCompanyInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "company_name": {
                    "type": "string"
                },
                "fax": {
                    "type": "string"
                },
                "postal_code": {
                    "type": "string"
                },
                "seal": {
                    "description": "path to seal image",
                    "type": "string"
                },
                "tel": {
                    "type": "string"
                }
            }
        },
        "models.PDFContractorInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "住所",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "person": {
                    "description": "担当",
                    "type": "string"
                },
                "recipient": {
                    "description": "受付",
                    "type": "string"
                },
                "tel": {
                    "description": "TEL",
                    "type": "string"
                }
            }
        },
        "models.PDFCustomerInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "company_name": {
                    "type": "string"
                },
                "fax": {
                    "type": "string"
                },
                "postal_code": {
                    "type": "string"
                },
                "tel": {
                    "type": "string"
                }
            }
        },
        "models.PDFEstimate": {
            "type": "object",
            "properties": {
                "customer": {
                    "$ref": "#/definitions/models.PDFCustomerInfo"
                },
                "estimate_no": {
                    "type": "string"
                },
                "issue_date": {
                    "type": "string"
                },
                "issuer": {
                    "$ref": "#/definitions/models.PDFCompanyInfo"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PDFLineItem"
                    }
                },
                "payment_terms": {
                    "type": "string"
                },
                "recipient": {
                    "description": "佐藤 様",
                    "type": "string"
                },
                "remarks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sub_total": {
                    "type": "number"
                },
                "tax": {
                    "type": "number"
                },
                "tax_rate": {
                    "type": "number"
                },
                "title": {
                    "type": "string"
                },
                "total": {
                    "type": "number"
                },
                "valid_period": {
                    "description": "days",
                    "type": "integer"
                }
            }
        },
        "models.PDFInstruction": {
            "type": "object",
            "properties": {
                "collector": {
                    "description": "控 - 収集先",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PDFCollectorInfo"
                        }
                    ]
                },
                "contractor": {
                    "description": "作業指示書 - 収集先",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PDFContractorInfo"
                        }
                    ]
                },
                "instruction_no": {
                    "type": "string"
                },
                "issue_date": {
                    "type": "string"
                },
                "items": {
                    "description": "作業内容",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PDFWorkItem"
                    }
                },
                "memo": {
                    "description": "メモ（印刷されません）",
                    "type": "string"
                },
                "work_details": {
                    "description": "作業詳細",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PDFWorkDetails"
                        }
                    ]
                }
            }
        },
        "models.PDFLineItem": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "quantity": {
                    "type": "number"
                },
                "unit": {
                    "type": "string"
                },
                "unit_price": {
                    "type": "number"
                }
            }
        },
        "models.PDFWorkDetails": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "集金額（税込）",
                    "type": "string"
                },
                "contractor": {
                    "description": "作業伝票",
                    "type": "string"
                },
                "extra_points": {
                    "description": "税抜@ ポイント",
                    "type": "boolean"
                },
                "manifest": {
                    "description": "マニフェスト",
                    "type": "string"
                },
                "manifest_type": {
                    "description": "Tポイント",
                    "type": "string"
                },
                "no_recycling_fee": {
                    "description": "リサイクル券無",
                    "type": "boolean"
                }
            }
        },
        "models.PDFWorkItem": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                }
            }
        },
        "models.UpdateEstimateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "hourly_rate": {
                    "type": "number",
                    "minimum": 0
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "total_lines": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "models.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "dispose_date": {
                    "description": "Format: yyyy/mmdd",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "utils.ErrorResponse": {
            "description": "Standard error response structure",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "エラーが発生しました"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "utils.Response": {
            "description": "Standard API response structure",
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "error": {
                    "type": "string",
                    "example": "エラーメッセージ"
                },
                "message": {
                    "type": "string",
                    "example": "成功しました"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:18080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Line Estimate API",
	Description:      "見積もり管理システムのAPI",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
